spring.application.name=JavaSpringBoot
spring.datasource.url=jdbc:mysql://localhost:3306/mysql_database
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret-key=my-super-secret-key-that-should-be-at-least-64-bytes-long-for-hs512-security