spring.application.name=JavaSpringBoot
spring.datasource.url=${DBMS_CONNECTION:jdbc:mysql://localhost:3306/mysql_database}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DBMS_USERNAME:root}
spring.datasource.password=${DBMS_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret-key=${SIGNERKEY_DEV:my-super-secret-key-that-should-be-at-least-64-bytes-long-for-hs512-security}
jwt.access-token-expiration=20
jwt.refresh-token-expiration=120